'use client';

import React from 'react';
import { AlertCircle, TrendingUp, Info } from 'lucide-react';
import { cn } from '@/lib/utils';

interface RedFlag {
  issue_summary: string;
  severity: 'low' | 'medium' | 'high';
  frequency_count: number;
}

interface RedFlagListProps {
  flags: RedFlag[];
}

export default function RedFlagList({ flags }: RedFlagListProps) {
  return (
    <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm h-full">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider">Red Flags</h3>
        <span className="bg-red-50 text-red-600 text-[10px] font-bold px-2 py-1 rounded uppercase tracking-tighter">
          {flags.length} Issues Found
        </span>
      </div>

      <div className="space-y-4">
        {flags.map((flag, index) => (
          <div key={index} className="flex items-start space-x-3 p-3 rounded-lg hover:bg-gray-50 transition-colors border border-transparent hover:border-gray-100">
            <div className={cn(
              "mt-0.5 rounded-full p-1",
              flag.severity === 'high' ? "bg-red-100 text-red-600" : 
              flag.severity === 'medium' ? "bg-orange-100 text-orange-600" : 
              "bg-yellow-100 text-yellow-600"
            )}>
              <AlertCircle size={14} />
            </div>
            <div className="flex-1">
              <p className="text-sm font-medium text-gray-900 leading-tight mb-1">
                {flag.issue_summary}
              </p>
              <div className="flex items-center space-x-3">
                <span className="text-[10px] text-gray-400 flex items-center">
                  <TrendingUp size={10} className="mr-1" />
                  Reported {flag.frequency_count} times
                </span>
                <span className={cn(
                  "text-[10px] font-bold uppercase tracking-widest",
                  flag.severity === 'high' ? "text-red-500" : 
                  flag.severity === 'medium' ? "text-orange-500" : 
                  "text-yellow-500"
                )}>
                  {flag.severity} priority
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 pt-6 border-t border-gray-50">
        <p className="text-[10px] text-gray-400 italic flex items-start">
          <Info size={10} className="mr-1 mt-0.5 flex-shrink-0" />
          Red flags are generated by cross-referencing complaints across multiple independent sources.
        </p>
      </div>
    </div>
  );
}
